
# Prerequisites: $KEY_FILE and $PROJECT setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/google-app-engine-deploy/src/master/README.md
# Your environment variables should also be declared in the app.yaml.template.

image: python:3.8

# Workflow Configuration

pipelines:
  branches:
    premium:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - pip
            script:
              - pip install -r requirements.txt
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
        # - step:
        #     name: Deploy to Production
        #     deployment: Production
        #     trigger: manual
        #     clone:
        #       enabled: false
        #     script:

